version: '3'
services:
  db:
    build:
      context: .
      dockerfile: pg.Dockerfile
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: bottlenose.Dockerfile
    volumes:
      - .:/bottlenose
    ports:
      - "3000:3000"
    depends_on:
      - db
